import { Poppins } from "next/font/google";
import "./globals.css";

// Componentes
import Nav from "@/components/inicio/nav";

const inter = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
